services:
  traefik:
    image: "traefik:v3.2"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./etc/traefik/traefik.yml:/etc/traefik/traefik.yml"